apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db-deployment
  namespace: <APP_NAME>
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: <APP_NAME>
        tier: backend
        type: database
    spec:
      containers:
        - name: postgresql
          image: postgres:9.6
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: <APP_NAME>
spec:
  selector:
    app: <APP_NAME>
    tier: backend
    type: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  namespace: <APP_NAME>
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
